# Generated by Django 2.2.17 on 2020-12-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0003_expresscheckouttransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpressCheckoutTransaction',
        ),
    ]
